### ISSUE TITLE
Create an option to reset the gyro offset when we shoot into the amp (in case there's a gyro drift)

### ISSUE THREAD

**Issue by batchen1** [FRC4048/FRC2024_Java#103]
This can be added as part of the amp shooting sequence, needs to know if we're red or blue

**Comment by neo-Aditya** [comment]
Do we have one? The closest I can find is the deploy Amp sequence

**Comment by noahheller** [comment]
> This can be added as part of the amp shooting sequence, needs to know if we're red or blue

The amp is on the same side for both alliances, so I don't think color will matter

**Comment by batchen1** [comment]
Closing as not needed. We updated the gyro scale factor on the NavX and now turning seems better.
